_target_: src.datamodules.dilepton.H5DataModule

train_conf:
  data_dir: ${paths.data_dir}
  met_kins: px,py
  lep_kins: px,py,pz,log_energy
  jet_kins: px,py,pz,log_energy
  nu_kins: px,py,pz
  file_list:
  # 테스트용으로 파일 하나만 사용
  - train_1.h5

test_conf:
  data_dir: ${paths.data_dir}
  met_kins: ${..train_conf.met_kins}
  lep_kins: ${..train_conf.lep_kins}
  jet_kins: ${..train_conf.jet_kins}
  nu_kins: ${..train_conf.nu_kins}
  file_list:
  - train_1.h5

loader_conf:
  pin_memory: False  # CPU에서는 False
  batch_size: 1024     # 작은 배치 사이즈
  num_workers: 6     # CPU에서는 worker 1개

val_frac: 0.1  # 검증 데이터 비율 증가
